language: rust
sudo: required
rust:
- stable
- beta
- nightly
  
before_cache: |
  if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi
script:
  - cargo clean
  - cargo test

after_success: |
  if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    bash <(curl -s https://codecov.io/bash) 
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libssl-dev #codecov
    - cmake
    - gcc
    - pkg-config #codecov
    - zlib1g-dev #codecov
    - binutils-dev
    - libiberty-dev
    - musl-tools
    - musl-dev